const statusPedido = [{
    0:'EM_TRATAMENTO',
    1:'EM_PREPARACAO',
    2:'SAIU_PARA_ENTREGA',
    3:'ADMIN_CONFIRMOU_ENTREGA',
    4:'USUARIO_CONFIRMOU_ENTREGA',
    5:'FINALIZADO',
    6:'VERIFICANDO_POSSIBILIDADE_ENTREGA',
    7:'ENVIADO_VALOR_FRETE'
}];